// Static assets only. User contracts and rate cache live in IndexedDB.
const PREFIX='subchike-static-'+new URL(self.registration.scope).pathname+'-';
const CACHE=PREFIX+'058e20db7d53c7d3';
const FILES=["./.nojekyll","./assets/index-D-5oh_YJ.css","./assets/index-DNw4Yoqh.js","./icons/apple-touch-icon.png","./icons/icon-192.png","./icons/icon-512.png","./index.html","./logos/ABEMALogo.jpg","./logos/AWALogo.jpg","./logos/AdobeCreativeCloudLogo.svg","./logos/AmazonMusicLogo.jpg","./logos/AmazonPrimeLogo.png","./logos/AppleArcadeLogo.jpg","./logos/AppleMusicLogo.jpg","./logos/AppleOneLogo.png","./logos/AppleTVLogo.jpg","./logos/AudibleLogo.jpg","./logos/AudiobookJPLogo.jpg","./logos/BitwardenLogo.jpg","./logos/BuyMeACoffeeLogo.jpg","./logos/CandFansLogo.png","./logos/CanvaLogo.jpg","./logos/ChatGPTLogo.png","./logos/CiEnLogo.svg","./logos/ClaudeLogo.jpg","./logos/CrunchyrollLogo.jpg","./logos/CursorLogo.jpg","./logos/DAZNLogo.jpg","./logos/DAnimeStoreLogo.jpg","./logos/DMMTVLogo.jpg","./logos/DiscordLogo.jpg","./logos/DisneyPlusLogo.jpg","./logos/DropboxLogo.jpg","./logos/DuolingoLogo.jpg","./logos/EvernoteLogo.jpg","./logos/FODLogo.jpg","./logos/FacebookLogo.jpg","./logos/FanboxLogo.png","./logos/FantiaLogo.png","./logos/GitHubCopilotLogo.jpg","./logos/GoogleAILogo.jpg","./logos/GoogleOneLogo.jpg","./logos/GoogleWorkspaceLogo.png","./logos/HuluLogo.jpg","./logos/ICloudLogo.jpg","./logos/InstagramLogo.jpg","./logos/KickLogo.jpg","./logos/KindleUnlimitedLogo.jpg","./logos/KoFiLogo.png","./logos/LINELogo.jpg","./logos/LINEMusicLogo.jpg","./logos/LeminoLogo.jpg","./logos/LinkedInLogo.jpg","./logos/MediumLogo.jpg","./logos/Microsoft365Logo.jpg","./logos/MyfansLogo.png","./logos/NetflixLogo.png","./logos/NiconicoLogo.jpg","./logos/NintendoSwitchOnlineLogo.png","./logos/NordVPNLogo.jpg","./logos/NoteLogo.jpg","./logos/NotionLogo.png","./logos/ObsidianLogo.jpg","./logos/OnePasswordLogo.jpg","./logos/OpenrecLogo.jpg","./logos/PatreonLogo.jpg","./logos/PerplexityLogo.jpg","./logos/PixivLogo.jpg","./logos/PlayStationPlusLogo.jpg","./logos/ProtonLogo.jpg","./logos/ReadwiseLogo.jpg","./logos/RedditLogo.jpg","./logos/SlackLogo.jpg","./logos/SnapchatLogo.jpg","./logos/SpotifyLogo.svg","./logos/StravaLogo.jpg","./logos/SubstackLogo.jpg","./logos/TELASALogo.jpg","./logos/TelegramLogo.jpg","./logos/TickTickLogo.jpg","./logos/TikTokLogo.jpg","./logos/TodoistLogo.jpg","./logos/TumblrLogo.jpg","./logos/TwitcastingLogo.jpg","./logos/TwitchLogo.jpg","./logos/UNextLogo.jpg","./logos/WOWOWLogo.jpg","./logos/XLogo.jpg","./logos/XboxGamePassLogo.jpg","./logos/YouTubeLogo.jpg","./logos/YouTubeMusicLogo.jpg","./logos/ZoomLogo.jpg","./manifest.webmanifest"];
const URLS=new Set(FILES.map(p=>new URL(p,self.registration.scope).href));
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES))));
// Wait for older app windows to close; do not replace code under an unsaved editor.
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);if(url.origin!==self.location.origin)return;
if(e.request.mode==='navigate'&&url.href.startsWith(self.registration.scope)){e.respondWith(caches.open(CACHE).then(c=>c.match(new URL('./index.html',self.registration.scope).href)).then(r=>r||fetch(e.request)));return;}
// The allowlist contains immutable same-origin public assets only. A server Vary: Origin must not distinguish module fetches from precache fetches.
if(URLS.has(url.href))e.respondWith(caches.open(CACHE).then(c=>c.match(e.request,{ignoreVary:true})).then(r=>r||fetch(e.request)));});
